---
- name: Download AccessDatabaseEngine_X64
  win_get_url:
      url: "{{ database_engine2016_url }}"
      dest: "{{ setup_folder }}"
      url_username: '{{ artifactory_username }}'
      url_password: '{{ artifactory_password }}'
      force: no
    
  tags: Microsoft AccessDatabaseEngine_X64

- name: install AccessDatabaseEngine_X64
 # win_shell: msiexec.exe /i {{setup_folder}}\{{ database_engine2016_filename }} /qn /norestart
  win_command: '{{setup_folder}}\{{ database_engine2016_filename }} /quiet'
