---
- name: Microsoft .NET Framework 4.7.2
  win_get_url:
      url: '{{ dotnet47_url }}'
      dest: '{{ setup_folder }}'
      url_username: '{{ artifactory_username }}'
      url_password: '{{ artifactory_password }}'
      force: no
    
  tags: Microsoft .NET Framework 4.7.2

- name: Installing Microsoft .NET Framework 4.7.2
  ansible.windows.win_package:
     path: "{{ setup_folder }}\\{{ dotnet47_filename }}"
     product_id: dotnet47
     arguments: /install /passive /norestart
  

